import type { Order, StockItem } from "./types";

export const stores = [
  { code: "LH", name: "Leather House" },
  { code: "LR", name: "La Reina" },
] as const;

export const workers = [
  { name: "Gustavo Rojas", area: "Estructura" },
  { name: "Jan Spork", area: "Corte" },
  { name: "Tony", area: "Costura" },
  { name: "LC01", area: "Tapiceria" },
  { name: "LG02", area: "Tapiceria" },
] as const;

export const orders: Order[] = [
  {
    id: "ord-001",
    code: "LH024",
    store: "LH",
    client: "Monica Pavez",
    product: "Sillon Domingo madera nogal",
    material: "Cuero natural",
    color: "Cognac",
    status: "in_production",
    condition: "Sin condicion",
    priority: "normal",
    isWarranty: false,
    entryDate: "2026-05-18",
    deliveryDate: "2026-06-08",
    assignedTo: "LC01",
    observations: "Cliente pide confirmar tono antes de tapizar.",
    steps: [
      { key: "structure", label: "Estructura", owner: "Gustavo Rojas", status: "done", completedAt: "2026-05-21" },
      { key: "cutting", label: "Corte", owner: "Jan Spork", status: "done", completedAt: "2026-05-23" },
      { key: "sewing", label: "Costura", owner: "Tony", status: "active", startedAt: "2026-05-28" },
      { key: "upholstery", label: "Tapiceria", owner: "LC01", status: "pending" },
      { key: "quality", label: "Revision", owner: "Rodrigo", status: "pending" },
    ],
  },
  {
    id: "ord-002",
    code: "LR003",
    store: "LR",
    client: "Elisa Navarrete",
    product: "Sofa Cubo 220x90 costura expuesta",
    material: "Cuero natural",
    color: "Riga Honey",
    status: "urgent",
    condition: "En bodega",
    priority: "critical",
    isWarranty: false,
    entryDate: "2026-05-14",
    deliveryDate: "2026-06-03",
    assignedTo: "LG02",
    observations: "Entrega comprometida. Revisar avance a diario.",
    steps: [
      { key: "structure", label: "Estructura", owner: "Gustavo Rojas", status: "done", completedAt: "2026-05-17" },
      { key: "cutting", label: "Corte", owner: "Jan Spork", status: "done", completedAt: "2026-05-19" },
      { key: "sewing", label: "Costura", owner: "Tony", status: "done", completedAt: "2026-05-25" },
      { key: "upholstery", label: "Tapiceria", owner: "LG02", status: "active", startedAt: "2026-05-27" },
      { key: "quality", label: "Revision", owner: "Rodrigo", status: "pending" },
    ],
  },
  {
    id: "ord-003",
    code: "LH025",
    store: "LH",
    client: "Maria Paz Concha",
    product: "Bergere segun foto",
    material: "Tela",
    color: "Negro BPR",
    status: "blocked",
    condition: "Sin condicion",
    priority: "high",
    isWarranty: false,
    entryDate: "2026-05-15",
    deliveryDate: "2026-06-04",
    assignedTo: "Tony",
    observations: "Falta confirmar material final.",
    steps: [
      { key: "structure", label: "Estructura", owner: "Gustavo Rojas", status: "done", completedAt: "2026-05-20" },
      { key: "cutting", label: "Corte", owner: "Jan Spork", status: "blocked", startedAt: "2026-05-24" },
      { key: "sewing", label: "Costura", owner: "Tony", status: "pending" },
      { key: "upholstery", label: "Tapiceria", owner: "LC01", status: "pending" },
      { key: "quality", label: "Revision", owner: "Rodrigo", status: "pending" },
    ],
  },
  {
    id: "ord-004",
    code: "LR004",
    store: "LR",
    client: "Janette Rojas",
    product: "Alfombra patchwork 325x245",
    material: "Cuero recuperado",
    color: "Mixto",
    status: "quality_control",
    condition: "Control de calidad",
    priority: "normal",
    isWarranty: true,
    entryDate: "2026-05-11",
    deliveryDate: "2026-06-07",
    assignedTo: "Rodrigo",
    observations: "Garantia, revisar terminacion y manchas.",
    steps: [
      { key: "structure", label: "Estructura", owner: "Gustavo Rojas", status: "done", completedAt: "2026-05-15" },
      { key: "cutting", label: "Corte", owner: "Jan Spork", status: "done", completedAt: "2026-05-18" },
      { key: "sewing", label: "Costura", owner: "Tony", status: "done", completedAt: "2026-05-25" },
      { key: "upholstery", label: "Tapiceria", owner: "LC01", status: "done", completedAt: "2026-05-30" },
      { key: "quality", label: "Revision", owner: "Rodrigo", status: "active", startedAt: "2026-06-01" },
    ],
  },
  {
    id: "ord-005",
    code: "LH026",
    store: "LH",
    client: "Pedro Schencke",
    product: "Sofa Modena Liso 240x95",
    material: "Cuero natural",
    color: "Waxy Camel",
    status: "scheduled",
    condition: "Sin condicion",
    priority: "normal",
    isWarranty: false,
    entryDate: "2026-05-28",
    deliveryDate: "2026-06-18",
    assignedTo: "LC01",
    observations: "Esperar confirmacion de cojines.",
    steps: [
      { key: "structure", label: "Estructura", owner: "Gustavo Rojas", status: "active", startedAt: "2026-06-01" },
      { key: "cutting", label: "Corte", owner: "Jan Spork", status: "pending" },
      { key: "sewing", label: "Costura", owner: "Tony", status: "pending" },
      { key: "upholstery", label: "Tapiceria", owner: "LC01", status: "pending" },
      { key: "quality", label: "Revision", owner: "Rodrigo", status: "pending" },
    ],
  },
];

export const stockItems: StockItem[] = [
  { id: "mat-001", name: "Cuero Riga Honey", category: "Cuero", unit: "m2", available: 28, minimum: 18, store: "general" },
  { id: "mat-002", name: "Cuero Waxy Camel", category: "Cuero", unit: "m2", available: 12, minimum: 16, store: "general" },
  { id: "mat-003", name: "Madera nogal", category: "Estructura", unit: "tablas", available: 42, minimum: 20, store: "LH" },
  { id: "mat-004", name: "Espuma alta densidad", category: "Relleno", unit: "planchas", available: 9, minimum: 12, store: "general" },
];
